palette = 'fish'

[palettes.fish]
directory =  '#E2FD3B'
error = '#d41e39'
# success = '#717375'
success = '#5fedaa'

[character]
success_symbol = '[\$](bold success)'
error_symbol = '[\$](bold error)'
vimcmd_symbol = '[âžœ](bold directory)'

[directory]
# style = 'bold directory'
